Work1/Bankingwebsite/bankingproject/bankingapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="index"),

]

Work1/Bankingwebsite/bankingproject/bankingproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from bankingproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankingapp.urls')),
    path('signup/',include('signup.urls')),
    path('form/',include('form.urls')),
]

if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Work1/Bankingwebsite/bankingproject/form/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('form',views.form,name='form'),

]

Work1/Bankingwebsite/bankingproject/signup/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.login,name="login"),
    path('logout',views.logout,name='logout'),
    path('switch',views.switch,name='switch',),

]

Work1/Bankingwebsite/bankingproject/bankingapp/models.py
from django.db import models

# Create your models here.

Work1/Bankingwebsite/bankingproject/form/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class UserProfile(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField(default=datetime.date(2024, 2, 27))
    number = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=6, choices=(('male', 'Male'), ('female', 'Female')))
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal = models.CharField(max_length=20)
    country = models.CharField(max_length=100)
    district = models.CharField(max_length=50, choices=(('district1', 'District 1'), ('district2', 'District 2'), ('district3', 'District 3')))
    account = models.CharField(max_length=50, choices=(('Current Account', 'Current Account'), ('Savings', 'Savings'), ('Business Account', 'Business Account')))
    credit_card = models.BooleanField(default=False,blank=True)
    debit_card = models.BooleanField(default=False,blank=True)
    cheque_book = models.BooleanField(default=False,blank=True)

    def __str__(self):
        return self.name

Work1/Bankingwebsite/bankingproject/signup/models.py
from django.db import models

# Create your models here.

Work1/Bankingwebsite/bankingproject/bankingapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, 'index.html')  # Corrected line

Work1/Bankingwebsite/bankingproject/form/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from form.models import UserProfile


def form(request):
    if request.method == 'POST':
        # username = request.POST['username']
        name = request.POST['name']
        dob = request.POST['dob']
        number = request.POST['number']
        gender = request.POST['gender']
        email = request.POST['email']
        street = request.POST['street']
        city = request.POST['city']
        state = request.POST['state']
        postal = request.POST['postal']
        country = request.POST['country']
        district = request.POST['district']
        account = request.POST['account']
        credit_card = request.POST.get('credit_card')
        debit_card = request.POST.get('debit_card')
        cheque_book = request.POST.get('cheque_book')

        user = UserProfile(
            # username=username,
            name=name,
            dob=dob,
            number=number,
            gender=gender,
            email=email,
            street=street,
            city=city,
            state=state,
            postal=postal,
            country=country,
            district=district,
            account=account,
            debit_card=debit_card,
            credit_card=credit_card,
            cheque_book=cheque_book,
        )
        user.save()

        messages.success(request, 'User profile created successfully.')

        return redirect('/')

    return render(request, "form.html")

Work1/Bankingwebsite/bankingproject/signup/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User

def logout(request):
    auth.logout(request)
    return redirect('/')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('switch')
        else:
            messages.info(request,"invalid credentials")
            return redirect ('login')

    return render(request,"login.html")

def switch(request):
    return redirect('form')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        confirmpass = request.POST['password1']
        if password == confirmpass:
            if User.objects.filter(username=username).exists():
                messages.info(request, "username allready taken")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, "email taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, first_name=firstname, last_name=lastname,
                                                email=email, password=password)

                user.save();
                print("User Created")
                return redirect('login')
        else:
            messages.info(request, "password not matching")
            return redirect("register")
        return redirect('/')
    return render(request, "signuppage.html")


from django.shortcuts import render, redirect

# Create your views here.

Work1/Bankingwebsite/bankingproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST">
    {% csrf_token %}
<!--    <input type="text" name="username" placeholder="Enter your username"><br>-->
    <input type="text" name="name" placeholder="name"><br>
    <input type="date" id="dob" name="dob"><br>
    <input type="number" id="age" name="number" placeholder="Enter your age" required><br>
    <label for="male">Male</label>
    <input type="radio" id="male" name="gender" value="male"><br>

    <label for="female">Female</label>
    <input type="radio" id="female" name="gender" value="female"><br>
    <input type="tel" id="phone" name="phone" placeholder="Enter your phone number"><br>
<!--    <input type="text" name="firstname" placeholder="Enter your Firstname"><br>-->
<!--    <input type="text" name="lastname" placeholder="Enter your Lastname"><br>-->
    <input type="email" name="email" placeholder="Enter your E-mail id"><br>

  <label>Address</label><br>

  <label for="street">Street:</label>
  <input type="text" id="street" name="street" placeholder="Enter your street address" required><br>

  <label for="city">City:</label>
  <input type="text" id="city" name="city" placeholder="Enter your city" required><br>

  <label for="state">State/Province:</label>
  <input type="text" id="state" name="state" placeholder="Enter your state or province" required><br>

  <label for="postal">Postal Code:</label>
  <input type="text" id="postal" name="postal" placeholder="Enter your postal code" required><br>

  <label for="country">Country:</label>
  <input type="text" id="country" name="country" placeholder="Enter your country" required><br>

   <label for="district">District:</label>
  <select id="district" name="district" required>
    <option value="">Select your district</option>
    <option value="district1">Malappuram</option>
    <option value="district2">Calicut</option>
    <option value="district3">Kochi</option>
    <option value="district3">Thrissur</option>
    <option value="district3">Thrivandrum</option>
    <!-- Add more options as needed -->
  </select>
    
    <label for="district">Account Type:</label>
  <select id="account" name="account" required>
    <option value="">Select your Account</option>
    <option value="Account1">Current Account</option>
    <option value="Account2">Savings</option>
    <option value="Account3">Business Account</option>

    <!-- Add more options as needed -->
  </select><br>



    <input type="checkbox" id="id_credit_card" name="credit_card" value="credit_card">
    <label for="id_credit_card">Credit Card</label><br>

    <input type="checkbox" id="id_debit_card" name="debit_card" value="debit_card">
    <label for="id_debit_card">Debit Card</label><br>

    <input type="checkbox" id="id_cheque_book" name="cheque_book" value="cheque_book">
    <label for="id_cheque_book">Cheque_Book</label><br>


<!--</form>-->


    <input type="submit">

</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

Work1/Bankingwebsite/bankingproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>
    <input type="password" name="password" placeholder="Enter Password"><br>
    <input type="submit">

</form>
</body>
</html>

Work1/Bankingwebsite/bankingproject/templates/signuppage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <input type="text" name="firstname" placeholder="Enter your Firstname"><br>
    <input type="text" name="lastname" placeholder="Enter your Lastname"><br>
    <input type="email" name="email" placeholder="Enter your E-mail id"><br>
    <input type="password" name="password" placeholder="Enter your Password"><br>
    <input type="password" name="password1" placeholder="Confirm Password"><br>
    <input type="submit">

</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

Work1/Bankingwebsite/bankingproject/templates/switch.html
<a href="signup/form">Click to Register Application</a>